# Generated by Django 4.2.6 on 2023-10-13 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('INIT', 'Initial'), ('STARTED', 'Started'), ('IN_PROCESS', 'In process'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='INIT', max_length=16)),
                ('scrapped_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LinkScrapped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('link', models.CharField(max_length=128)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.webpage')),
            ],
        ),
    ]
