# Generated by Django 4.2.6 on 2023-10-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_webpage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='page',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
